import Head from "next/head";
import AppLayout from "../components/AppLayout";
import HomeMenu from "../components/HomeMenu";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Copiloto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLayout>
          <HomeMenu />
      </AppLayout>
      <style jsx global>
        {`
          .container {
            display: flex;
            flex-direction: column;
            justify-content: space-between;
            align-items: center;
            height: 100vh;
          }
          main {
            background-image: url("/city.png");
            background-size: cover;
            width: 100%;
            height: 100%;
            opacity: 0.95;
          }
        `}
      </style>
    </div>
  );
}
