import Head from "next/head"
import Image from "next/image"
import styles from "../styles/Home.module.css"
import HomeMenu from './components/HomeMenu'

import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Copiloto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.header}>
        <picture>
          <img src="/Foton.svg" alt="" />
        </picture>
        <picture>
          <img src="/coPiloto.svg" alt="" />
        </picture>
        <picture>
          <img src="/kaufman.svg" alt="" />
        </picture>
      </header>
      <main className={styles.main}>
        <HomeMenu />
      </main>
      <footer className={styles.footer}>
        <div className="copyr">
          <span>Copyright © 2021 eTrans.cl | Credits</span>
        </div>
        <div className="poweredb">
          <span>Powered by eTrans.cl</span>
        </div>
      </footer>
    </div>
  );
}
